### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by bawat** [GZJ/min2tray#1]
Example command line argument is wrong.

min2tray -c="alacritty.exe --working-directory . -t  alacritty"  -w="alacritty"  -i="icon.png" -k='<ctrl>+<alt>+a'

Should be

min2tray -c="alacritty.exe --working-directory . -t  alacritty"  -w="alacritty"  -i="icon.png" -k="<ctrl>+<alt>+a"

**Comment by GZJ** [comment]
Thank you for fixing this issue.
